config/routes.rb
Rails.application.routes.draw do
  # IEの場合は警告ページに転送
  constraints TridentBrowserConstraint do
    get '/' => redirect('/not-support-trident-browser.html')
    get '/:path' => redirect('/not-support-trident-browser.html')
    get '/:path/:to' => redirect('/not-support-trident-browser.html')
    get '/admin/:path/:to' => redirect('/not-support-trident-browser.html')
  end

  root 'front_page#index'

  namespace :admin do
    # 非ログイン状態の場合はログインページに転送
    constraints LoginConstraint do
      get 'login' => 'login#index'
      get '/' => redirect('/admin/login')
      get '/:path' => redirect('/admin/login')
    end

    root 'dashboard#index'

    get 'login' => 'login#index'
    post 'login' => 'login#create'
    delete 'logout' => 'login#destory'

    get 'post/edit'
    get 'post/new'
    get 'post' => 'post#index'
    post 'post' => 'post#create'
    patch 'post' => 'post#update'
    delete 'post' => 'post#destory'

    get 'category/edit'
    get 'category' => 'category#index'
    post 'category' => 'category#create'
    patch 'category' => 'category#update'
    delete 'category' => 'category#destory'

    get 'tag/edit'
    get 'tag' => 'tag#index'
    post 'tag' => 'tag#create'
    patch 'tag' => 'tag#update'
    delete 'tag' => 'tag#destory'

    get 'media/edit'
    get 'media/new'
    get 'media' => 'media#index'
    post 'media' => 'media#create'
    patch 'media' => 'media#update'
    delete 'media' => 'media#destory'

    get 'user/edit'
    get 'user/new'
    post 'user/confirm' => 'user#confirm'
    get 'user' => 'user#index'
    post 'user' => 'user#create'
    patch 'user' => 'user#update'
    delete 'user' => 'user#destory'

    get 'setting' => 'setting#index'
    patch 'setting' => 'setting#update'
  end

  namespace :api do
    post 'markdown-parser' => 'markdown#parse'
    post 'add-categories' => 'category#create'
    post 'add-tags' => 'tag#create'
    post 'media-upload' => 'media#create'
  end

  get 'search' => 'search#index'
  get '/:slug' => 'blog#term'
  get '/:category/:postname' => 'blog#post'
end

app/views/_includes/_article-list.html.erb
<% @posts.each do |post| %>
<article class="p-article-list__item" itemscope itemtype="https://schema.org/BlogPosting">
<div class="p-article-list__content p-layout-article">
<div class="p-layout-article__content">
<a href="/<%= post.category.term.slug %>" class="c-link-category" style="background: <%= post.category.color %>"><span itemprop="keywords"><%= post.category.name %></span></a>
<h2 class="p-layout-article__header" itemprop="headline"><a href="/<%= post.category.term.slug %>/<%= post.postname %>" rel="bookmark" class="p-layout-article__link" itemprop='mainEntityOfPage'><%= post.title %></a></h2>
<p class="p-layout-article__desc"><%= post.post_option.description %></p>
</div>
<% unless post.thumbnail.nil? %>
<% image_size = MiniMagick::Image.new(Rails.root.join('public', post.thumbnail.image.url.to_s[1..-1])).dimensions %>
<div class="p-layout-article__media" itemprop="image" itemscope itemtype="https://schema.org/ImageObject">
<noscript class="loading-lazy">
<%= image_tag post.thumbnail.image.url, {alt: '', class: 'p-layout-article__image', decoding: 'async', loading: 'lazy', width: image_size[0], height: image_size[1]} %>
</noscript>
<meta itemprop="url" content="<%= "#{post.thumbnail.image.url}" %>">
<meta itemprop="width" content="<%= image_size[0] %>">
<meta itemprop="height" content="<%= image_size[1] %>">
</div>
<% end %>
</div>
<p class="p-article-list__published" itemprop="datePublished dateModified" datetime="<%= l post.published_at, format: :hyphenation %>" content="<%= l post.published_at, format: :hyphenation %>"><%= l post.published_at, format: :date %></p>
<div class="p-article-list__tag">
<ul class="p-linklist-tags">
<% post.tags.each do |tag| %>
<li class="p-linklist-tags__item"><a href="/<%= tag.term.slug %>" class="p-linklist-tags__link"><span itemprop="keywords"><%= tag.name %></span></a></li>
<% end %>
</ul>
</div>

<div class="u-display-none" itemprop="author" itemscope itemtype="https://schema.org/Person" hidden>
<meta itemprop="name" content="<%= post.user.display_name %>">
</div>

<div class="u-display-none" itemprop="publisher" itemscope itemtype="https://schema.org/Organization" hidden>
<div class="u-display-none" itemprop="logo" itemscope itemtype="https://schema.org/ImageObject" hidden>
<meta itemprop="url" content="/images/publisher-logo.png">
</div>
<meta itemprop="name" content="<%= @settings.site_name %>">
</div>
</article>
<% end %>

app/views/_includes/_flash.erb
<% unless flash.empty? %>
<% flash.each do |message_type, message| %>
<div class="admin-flash admin-flash--<%= message_type %> js-flash-message" role="status" aria-live="<%= message_type == 'error' || message_type == 'alert' ? 'assertive' : 'polite' %>">
<div class="admin-flash__text" aria-atomic="true"><span class="admin-flash__type"><%= message_type.capitalize %></span><%= message %></div>
</div>
<% end %>
<% flash.clear %>
<% end %>

app/views/_includes/_flash.html.erb
<% unless flash.empty? %>
<% flash.each do |message_type, message| %>
<div class="admin-flash admin-flash--<%= message_type %> js-flash-message" role="status" aria-live="<%= message_type == 'error' || message_type == 'alert' ? 'assertive' : 'polite' %>">
<div class="admin-flash__text" aria-atomic="true"><span class="admin-flash__type"><%= message_type.capitalize %></span><%= message %></div>
</div>
<% end %>
<% flash.clear %>
<% end %>

app/views/_includes/_footer.html.erb
<footer class="l-footer">
<div class="l-footer-pageTop">
<a href="#top" class="l-footer-pageTop__link js-smooth-scroll"><span class="u-altText">ページの先頭へ</span></a>
</div>
<div class="l-footer-content">
<div class="l-footer-content__column">
<div class="p-heading-lv3">
<h2 class="p-heading-lv3__title">Operator</h2>
</div>
<div class="p-layout-operator">
<div class="p-layout-operator__content">
<p class="c-text-lead"><b class="c-text-bold">すーぱーぷれっそ</b></p>
<div class="p-layout-operator__description">
<p class="c-text">エスプレッソコーヒー</p>
<p class="c-text">趣味が趣味で趣味なんです。まあ、趣味ですから。</p>
</div>
<ul class="p-linklist-social">
<li class="p-linklist-social__item"><a href="https://twitter.com/super_presso" target="_blank" rel="noopener" class="p-linklist-social__link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46 46" width="28" height="28" focusable="false"><g><circle style="fill:#1d9bf0;" cx="23" cy="23" r="23"/><path style="fill:#fff;" d="M19.17 35.13a15.67 15.67 0 0 0 15.83-15.77v-.72a11.28 11.28 0 0 0 2.77-2.87 11 11 0 0 1-3.19.87 5.49 5.49 0 0 0 2.42-3.07 11 11 0 0 1-3.52 1.35 5.55 5.55 0 0 0-9.59 3.79 5.88 5.88 0 0 0 .11 1.29 15.73 15.73 0 0 1-11.43-5.8 5.62 5.62 0 0 0-.77 2.8 5.56 5.56 0 0 0 2.47 4.62 5.48 5.48 0 0 1-2.51-.7v.08a5.55 5.55 0 0 0 4.45 5.44 5.49 5.49 0 0 1-1.47.19 5.16 5.16 0 0 1-1-.1 5.54 5.54 0 0 0 5.18 3.85 11.12 11.12 0 0 1-6.92 2.34 11.73 11.73 0 0 1-1.33-.08 15.74 15.74 0 0 0 8.5 2.49"/></g></svg><span class="u-altText">Twitter</span></a></li>
<li class="p-linklist-social__item"><a href="https://github.com/express-espresso" target="_blank" rel="noopener" class="p-linklist-social__link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="28" height="28"><path style="fill:#000;" d="M22.39 6.13a12 12 0 0 0-4.39-4.48 11.5 11.5 0 0 0-6-1.65 11.48 11.48 0 0 0-6 1.65 12 12 0 0 0-4.39 4.48 12.27 12.27 0 0 0-1.61 6.17 12.13 12.13 0 0 0 2.29 7.23 11.87 11.87 0 0 0 5.91 4.47.7.7 0 0 0 .63-.12.63.63 0 0 0 .2-.48v-2.31l-.36.07a4.42 4.42 0 0 1-.87.05 6 6 0 0 1-1.1-.11 2.41 2.41 0 0 1-1-.48 2 2 0 0 1-.69-1l-.16-.37a3.92 3.92 0 0 0-.49-.82 1.89 1.89 0 0 0-.68-.61l-.11-.08a1.19 1.19 0 0 1-.2-.19.9.9 0 0 1-.14-.22.14.14 0 0 1 .08-.19.94.94 0 0 1 .45-.07l.31.05a2.16 2.16 0 0 1 .77.38 2.63 2.63 0 0 1 .76.83 2.82 2.82 0 0 0 .87 1 1.8 1.8 0 0 0 1 .34 4.51 4.51 0 0 0 .89-.08 2.83 2.83 0 0 0 .71-.24 2.61 2.61 0 0 1 .76-1.65 9.76 9.76 0 0 1-1.6-.29 6.44 6.44 0 0 1-1.47-.62 4.4 4.4 0 0 1-1.26-1.08 5.26 5.26 0 0 1-.82-1.68 8.25 8.25 0 0 1-.32-2.4 4.76 4.76 0 0 1 1.24-3.3 4.38 4.38 0 0 1 .11-3.27 2.18 2.18 0 0 1 1.29.25 9.85 9.85 0 0 1 1.31.62l.69.43a10.92 10.92 0 0 1 6 0l.59-.36a8.79 8.79 0 0 1 1.41-.73 2.09 2.09 0 0 1 1.27-.18 4.34 4.34 0 0 1 .12 3.27 4.76 4.76 0 0 1 1.24 3.3 8.37 8.37 0 0 1-.32 2.41 5.07 5.07 0 0 1-.83 1.68 4.44 4.44 0 0 1-1.27 1.07 6.09 6.09 0 0 1-1.47.62 9.56 9.56 0 0 1-1.6.29 2.89 2.89 0 0 1 .86 2.27v3.38a.63.63 0 0 0 .2.48.68.68 0 0 0 .62.12 11.83 11.83 0 0 0 5.91-4.45 12.13 12.13 0 0 0 2.27-7.23 12.27 12.27 0 0 0-1.61-6.17z"/></svg><span class="u-altText">GitHub</span></a></li>
</ul>
</div>
<div class="p-layout-operator__media">
<noscript class="loading-lazy">
<img src="/images/users/user_image_1.png" alt="" loading="lazy" decoding="async" class="p-layout-operator__image" width="120" height="120">
</noscript>
</div>
</div>
</div>
<div class="l-footer-content__column l-footer-content__column--mini">
<div class="p-heading-lv3">
<h2 class="p-heading-lv3__title">This Blog</h2>
</div>
<div class="p-text p-text--closely">
<p class="c-text">このブログはすーぱーぷれっそがRuby on Railsを使用し、開発しています！</p>
<p class="c-text">以下にて、ソースコードを公開しておりますので、ご指摘等お願いいたします！</p>
</div>

<div class="p-button-icon p-button-icon--end">
<a href="https://github.com/express-espresso/s-presso" target="_blank" rel="noopener" class="c-button-icon c-button-icon--github">見に行く</a>
</div>

</div>
</div>
<p class="l-footer-copy"><small class="l-footer-copy__text">© 2021 S'Presso</small></p>
</footer>

app/views/_includes/_header.html.erb
<header class="l-header">
<div class="l-header__inner">
<div class="l-header__logo">
<% if request.path == '/' %>
<h1 class="p-header-logo"><a href="/" class="p-header-logo__link"><%= image_tag('logo-with-name-01.svg', {alt: "S'Presso", class: 'p-header-logo__image', width: '140', height: '42', decoding: 'async'}) %></a></h1>
<% else %>
<p class="p-header-logo"><a href="/" class="p-header-logo__link"><%= image_tag('logo-with-name-01.svg', {alt: "S'Presso", class: 'p-header-logo__image', width: '140', height: '42', decoding: 'async'}) %></a></p>
<% end %>
</div><!-- /.l-header__logo -->

<a href="/search" class="c-link-search u-narrowNone"><span class="u-altText">検索ページ</span></a>
</div><!-- /.l-header__inner -->
</header>

app/views/_includes/_main-visual.erb
<div class="l-main__main-visual">
<div class="p-media-mainVisual">
<div class="p-media-mainVisual__content">
<div class="p-text p-text--center">
<b class="c-text-heading"><%= image_tag 'logo-text.svg', {class: 'c-text-heading__image', alt: "S'Presso", width: '140', height: '42', decoding: 'async'} %></b>
<p class="c-text-lead"><%= @settings.site_catch %></p>
</div>
</div>
<%= image_tag 'img_main-visual.png', {class: 'p-media-mainVisual__image', alt: '', width: '516', height: '324', decoding: 'async'} %>
</div>
</div>

app/views/_includes/_meta.html.erb
<%
base_url = @settings.site_url.sub(/\/$/, '') || request.base_url
is_404 = response.status.to_s == '404'
no_ogp = true
page_title = ''
description = ''

case request.path
when '/' then
  no_ogp = false
  page_title = "#{@settings.site_name} | #{@settings.site_catch}"
  description = "#{@settings.site_catch}。#{@settings.site_name}は主にプログラミングについて学んだことをまとめるブログです。"
  preload_image = asset_path('img_main-visual.png')
when '/search' then
  page_title = "検索結果 | #{@settings.site_name}"
  description = '検索キーワードに関連した記事一覧ページです。'
else
  if is_404
    page_title = "お探しのページが見つかりませんでした | #{@settings.site_name}"
    preload_image = asset_path('img_notfound.png')
  else
    no_ogp = false
    page_title = @post.nil? ? "#{@term.name} | #{@settings.site_name}" : "#{@post.title} | #{@settings.site_name}"

    if @post.nil?
      description = "#{@term_type == 'category' ? 'カテゴリー' : 'タグ'}が「#{@term.name}」の記事一覧ページです。"
    else
      description = @post.post_option.description
      preload_image = @post.try(:thumbnail).nil? ? nil : @post.thumbnail.image.url
    end
  end
end
%>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<title><%= page_title %></title>
<meta name="description" itemprop="description" content="<%= description %>">

<% unless @post.nil? %>
<%= '<meta name="robots" content="noindex">'.html_safe if @post.post_option.noindex %>
<%= '<meta name="robots" content="nofollow">'.html_safe if @post.post_option.nofollow %>
<% end %>

<% if no_ogp %>
<meta name="robots" content="noindex">
<% else %>
<meta property="og:title" content="<%= page_title %>">
<meta property="og:locale" content="ja_JP">
<meta property="og:type" content="blog">
<meta property="og:url" content="<%= base_url + request.path %>">
<meta property="og:image" content="<%= "#{base_url}#{preload_image.nil? ? '/images/default-ogp-image.png' : preload_image}" %>">
<meta property="og:site_name" content="<%= @settings.site_name %>">
<meta property="og:description" content="<%= description %>">
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@super_presso">
<link rel="canonical" href="<%= base_url + request.path %>">
<% end %>

<% unless preload_image.nil? %>
<link rel="preload" as="image" href="<%= preload_image %>">
<% end %>

<link rel="apple-touch-icon-precomposed" href="/apple-touch-icon.png">

app/views/_includes/_nav.html.erb
<div class="l-nav js-toggle-menu__content">
<div class="l-nav__inner">
<nav class="p-nav" aria-labelledby="nav-main">
<div class="p-heading-hidden">
<h2 id="nav-main" class="p-heading-hidden__title">メインメニュー</h2>
</div><!-- /.p-heading-hidden -->

<form method="get" action="/search" class="p-form-search u-wideNone">
<div class="c-form-min-search">
<input type="text" name="keyword" class="c-form-min-search__input" placeholder="Search in site" title="Search in site">
<button type="submit" class="c-form-min-search__submit"><span class="u-altText">検索</span></button>
</div><!-- /.c-form-min-search -->
</form><!-- /.p-form-search -->

<div class="p-nav-item">
<div class="p-heading-weak">
<h2 class="p-heading-weak__title">Categories</h2>
</div><!-- /.p-heading-weak -->

<div class="p-linklist-category">
<ul class="p-linklist-category__list">
<% Category.eager_load(:term).preload(:posts).order(:name).each do |category| %>
<% next if @published_posts.where('category_id = ?', category).length.zero? %>
<li class="p-linklist-category__item"><span class="p-linklist-category__mark" style="background: <%= category.color %>"></span><a href="/<%= category.term.slug %>" class="p-linklist-category__link"><%= category.name %></a></li>
<% end %>
</ul>
</div><!-- /.p-linklist-category -->
</div><!-- /.p-nav__item -->

<div class="p-nav-item">
<div class="p-heading-weak">
<h3 class="p-heading-weak__title">Tags</h3>
</div><!-- /.p-heading-weak -->

<div class="p-linklist-tag">
<ul class="p-linklist-tag__list">
<% Tag.eager_load(:term).preload(:posts).order(:name).each do |tag| %>
<% next if tag.posts.where('status = ? and published_at <= ?', 'publish', DateTime.now).length.zero? %>
<li class="p-linklist-tag__item"><a href="/<%= tag.term.slug %>" class="p-linklist-tag__link"><%= tag.name %></a></li>
<% end %>
</ul>
</div><!-- /.p-linklist-category -->
</div><!-- /.p-nav__item -->
</nav><!-- /.p-nav -->
</div><!-- /.l-nav__inner -->
</div><!-- /.l-nav -->

app/views/_includes/_search-form.html.erb
<% is_front_page = request.path == '/' %>

<div class="l-search">
<div class="l-search__form">
<form method="get" action="/search" class="p-form-search">
<div class="c-form-search">
<input type="text" name="keyword" class="c-form-search__input" placeholder="Search in site" title="Search in site">
<button type="submit" class="c-form-search__submit"><span class="u-altText">検索</span></button>
</div><!-- /.c-form-search -->
</form><!-- /.p-form-search -->
</div>
</div>

app/views/_includes/_share-buttons.html.erb
<%
base_url = @settings.site_url || request.base_url
base_url.to_s.sub!(/\/{0,}$/, '')
page_url = URI.encode_www_form_component("#{base_url}#{request.path}")
%>

<div class="p-linklist-share">
<ul class="p-linklist-share__list">
<li class="p-linklist-share__item"><a href="https://twitter.com/intent/tweet?url=<%= page_url %>&text=<%= URI.encode_www_form_component("#{@post.title} - #{@settings.site_name}") %>&via=super_presso" target="_blank" rel="nofollow noopener noreferrer" class="p-linklist-share__link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46 46" width="46" height="46" focusable="false"><g><circle style="fill:#1d9bf0;" cx="23" cy="23" r="23"/><path style="fill:#fff;" d="M19.17 35.13a15.67 15.67 0 0 0 15.83-15.77v-.72a11.28 11.28 0 0 0 2.77-2.87 11 11 0 0 1-3.19.87 5.49 5.49 0 0 0 2.42-3.07 11 11 0 0 1-3.52 1.35 5.55 5.55 0 0 0-9.59 3.79 5.88 5.88 0 0 0 .11 1.29 15.73 15.73 0 0 1-11.43-5.8 5.62 5.62 0 0 0-.77 2.8 5.56 5.56 0 0 0 2.47 4.62 5.48 5.48 0 0 1-2.51-.7v.08a5.55 5.55 0 0 0 4.45 5.44 5.49 5.49 0 0 1-1.47.19 5.16 5.16 0 0 1-1-.1 5.54 5.54 0 0 0 5.18 3.85 11.12 11.12 0 0 1-6.92 2.34 11.73 11.73 0 0 1-1.33-.08 15.74 15.74 0 0 0 8.5 2.49"/></g></svg><span class="u-altText">Twitterでシェアする</span></a></li>
<li class="p-linklist-share__item"><a href="https://www.facebook.com/sharer/sharer.php?u=<%= page_url %>" target="_blank" rel="nofollow noopener noreferrer" class="p-linklist-share__link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46 46" width="46" height="46" focusable="false"><g><path style="fill:#1877f2;" d="M46 23a23 23 0 1 0-26.59 22.72v-16.07h-5.84v-6.65h5.84v-5.07c0-5.76 3.43-8.95 8.68-8.95a35.28 35.28 0 0 1 5.15.45v5.66h-2.9c-2.86 0-3.75 1.78-3.75 3.6v4.31h6.41l-1 6.65h-5.41v16.07a23 23 0 0 0 19.41-22.72z"/><path style="fill:#fff;" d="M32 29.65l1-6.65h-6.41v-4.31c0-1.82.89-3.6 3.75-3.6h2.9v-5.66a35.28 35.28 0 0 0-5.15-.43c-5.25 0-8.68 3.19-8.68 9v5h-5.84v6.65h5.84v16.07a23.15 23.15 0 0 0 7.18 0v-16.07z"/></g></svg><span class="u-altText">Facebookでシェアする</span></a></li>
<li class="p-linklist-share__item"><a href="http://b.hatena.ne.jp/add?&url=<%= page_url %>" target="_blank" rel="nofollow noopener noreferrer" class="p-linklist-share__link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46 46" width="46" height="46" focusable="false"><g><circle style="fill:#00a4de;" cx="23" cy="23" r="23"/><path style="fill:#fff;" d="M25.59 23.75a4.9 4.9 0 0 0-3.47-1.57 5.65 5.65 0 0 0 2.88-1.59 4.2 4.2 0 0 0 .9-2.82 5.19 5.19 0 0 0-.61-2.5 4.55 4.55 0 0 0-1.77-1.71 7.59 7.59 0 0 0-2.41-.79 34.92 34.92 0 0 0-4.94-.22h-5.72v20.9h5.91a38.28 38.28 0 0 0 5.13-.24 8.15 8.15 0 0 0 2.63-.82 4.8 4.8 0 0 0 2-2 6 6 0 0 0 .71-3 5.32 5.32 0 0 0-1.24-3.64zm-9.84-6.57h1.25a5.92 5.92 0 0 1 2.86.47 1.86 1.86 0 0 1 .72 1.66 1.69 1.69 0 0 1-.78 1.6 6.17 6.17 0 0 1-2.89.46h-1.16v-4.19zm4.86 12a5.86 5.86 0 0 1-2.86.51h-2v-4.57h2.08a5.39 5.39 0 0 1 2.84.52 2.07 2.07 0 0 1 .78 1.84 1.72 1.72 0 0 1-.85 1.69zM32.9 28.16a2.65 2.65 0 1 0 2.65 2.65 2.65 2.65 0 0 0-2.65-2.65zM30.6 12.55h4.6v13.94h-4.6z"/></g></svg><span class="u-altText">このエントリーをはてなブックマークに追加する</span></a></li>
<li class="p-linklist-share__item"><a href="https://getpocket.com/edit?url=<%= page_url %>" target="_blank" rel="nofollow noopener noreferrer" class="p-linklist-share__link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46 46" width="46" height="46" focusable="false"><g><circle style="fill:#ef4056;" cx="23" cy="23" r="23"/><path style="fill:#fff;" d="M16.23 15.24a1.41 1.41 0 0 0-1.46 1.51v5.56c0 4.52 4.49 8.06 8.37 8 4.37 0 8.4-3.72 8.4-8v-5.56a1.44 1.44 0 0 0-1.54-1.51zm3.54 4.53l3.37 3.23 3.37-3.2c1.51-.64 2.17 1.08 1.55 1.59l-4.39 4.19a1.39 1.39 0 0 1-1.06 0l-4.39-4.19c-.59-.56.18-2.31 1.55-1.59z"/></g></svg><span class="u-altText">Pocketであとで読む</span></a></li>
<li class="p-linklist-share__item"><a href="https://social-plugins.line.me/lineit/share?url=<%= page_url %>" target="_blank" rel="nofollow noopener noreferrer" class="p-linklist-share__link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 46 46" width="46" height="46" focusable="false"><g><circle style="fill:#00b900;" cx="23" cy="23" r="23"/><path style="fill:#fff;" d="M38.3 21.62c0-6.85-6.86-12.42-15.3-12.42s-15.3 5.57-15.3 12.42c0 6.14 5.44 11.28 12.8 12.25.49.11 1.17.33 1.34.75a3.11 3.11 0 0 1 .05 1.38l-.22 1.3c-.06.39-.3 1.52 1.33.83s8.81-5.13 12-8.87a11 11 0 0 0 3.28-7.64"/><path style="fill:#00b900;" d="M19.89 18.31h-1.07a.29.29 0 0 0-.3.3v6.66a.29.29 0 0 0 .3.3h1.07a.29.29 0 0 0 .3-.3v-6.66a.29.29 0 0 0-.3-.3M27.28 18.31h-1.08a.29.29 0 0 0-.29.3v4l-3.06-4.13h-1.32a.3.3 0 0 0-.3.3v6.66a.3.3 0 0 0 .3.3h1.07a.29.29 0 0 0 .3-.3v-4.12l3.1 4.13a.27.27 0 0 0 .08.07h1.24a.3.3 0 0 0 .3-.3v-6.61a.3.3 0 0 0-.3-.3M17.3 23.9h-2.91v-5.29a.29.29 0 0 0-.3-.3h-1.09a.29.29 0 0 0-.3.3v6.66a.3.3 0 0 0 .08.21.32.32 0 0 0 .21.08h4.31a.29.29 0 0 0 .3-.3v-1.06a.3.3 0 0 0-.3-.3"/><path style="fill:#00b900;" d="M33.2 20a.29.29 0 0 0 .3-.3v-1.09a.29.29 0 0 0-.3-.3h-4.28a.3.3 0 0 0-.21.08.32.32 0 0 0-.08.21v6.66a.3.3 0 0 0 .08.21.3.3 0 0 0 .21.08h4.28a.29.29 0 0 0 .3-.3v-1.05a.3.3 0 0 0-.3-.3h-2.91v-1.12h2.91a.3.3 0 0 0 .3-.3v-1.08a.29.29 0 0 0-.3-.29h-2.91v-1.11z"/></g></svg><span class="u-altText">LINEでシェアする</span></a></li>
</ul>
</div>